description = "Test JSON file"
features = ["json", "yaml", "toml"]
name = "asp_cli"
version = "0.1.0"

[config]
debug = true
host = "localhost"
port = 8080

[metadata]
author = "Test User"
created = "2025-11-16"
